[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CodecZstd = "6b39b394-51ab-5f42-8807-6242bab2b4c2"
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MemoryConstrainedTreeBoosting = "892701ce-1da2-11e9-2428-fd1c8d726794"
PNGFiles = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Proj4 = "9a7e659c-8ee8-5706-894e-f68f43bc57ea"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
